theme: jekyll-theme-slate
title: Третье Обращение к Человечеству
description: К разумным жителям Земли, к расе, называющей себя Человечеством, обращается Коа-лиционный Отряд Наблюдателей (К.О.Н.). Передано посредниками Шамбалы Е.И. Рерих и Н.К. Рерих.
